### ISSUE TITLE
Null safety support?

### ISSUE THREAD

**Issue by DowsingUK** [gokul1630/root#1]
Is this plugin gettin null safety support?

**Comment by umityayla** [comment]
@DowsingUK I know I'm very late to the party but I forked the repo and migrated it To use my repo you can add the following lines to your `pubspec.yaml`

```
dependencies:
  root:
    git:
      url: git://github.com/umityayla/root.git
      ref: main
```
